name: ci pipeline
on:
    push:
        branches:
            - master
            - marking
            - listing
    pull_request:
        branches:
            - master
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.11
            
            - name: Run unittests
              run: |
                  python3 -m unittest discover tests
